[versions]
agp = "9.2.1"
kotlin = "2.3.21"
android-minSdk = "26"
android-compileSdk = "37"
kotlinx-io = "0.9.0"
ksoup = "0.2.6"
korlibs = "6.0.0"
konanplugin = "1.2.0-alpha06"
kotlinx-resources = "0.15.0"
junit = "6.1.0"
detekt = "1.23.8"
ktfmt = "0.27.0"
konsist = "0.17.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
korlibs-compression = { module = "com.soywiz:korlibs-compression", version.ref = "korlibs" }
kotlinx-resources = { module = "com.goncalossilva:resources", version.ref = "kotlinx-resources" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-resources = { id = "com.goncalossilva.resources", version.ref = "kotlinx-resources" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
konanplugin = { id = "io.github.lemcoder.konanplugin", version.ref = "konanplugin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
